# -*- coding: utf-8 -*-
"""Streamlit.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18VOgl1rPyvW-544-6_YDpvagsaHR5iKR
"""

import streamlit as st
import cohere

# Initialize Cohere client
co = cohere.Client("PVEQsOX8eE4PuQpewnNupCnohAgLiZNe21xLo5dg")

def main():
    st.title("Cohere Chat App")

    # Get user input
    user_input = st.text_input("Ask a question:")

    if st.button("Ask"):
        # Perform chat with Cohere API
        response = co.chat(message=user_input, model="command", connectors=[{"id": "web-search"}])

        # Display the response
        st.text("Cohere's Answer:")
        st.text(response)


if __name__ == "__main__":
    main()

